-- Emerald support for Dialogue Portraits (Gen 3).
--
-- ---- why this file exists, and why it is a separate tree
--
-- Everything else in this repository is FireRed / LeafGreen.  The mod's own
-- header says so, and every data table it ships -- art/trainer_ids.lua,
-- art/map_art.lua, art/crops.lua, the GFX_ART / SPRITE_ART tables in main.lua --
-- is keyed to facts that only exist IN THOSE TWO CARTS:
--
--   * the ScriptKey `g3:XXXXXXXX` the FRLG importer stamps on every map object;
--   * the FRLG graphics-id space (GFX_ART[25] = 103, and so on);
--   * the FRLG map-id spelling (FR_ROUTE_24, ...);
--   * the FRLG trainer CLASS vs trainer PIC number spaces, which are two
--     different spaces in FRLG and a third, different thing in Emerald;
--   * the 240x160 FireRed message box and the FireRed latin_normal font, both
--     of which the mod's seams (src.ui.game3.message / chrome / frlg_font) are.
--
-- Pokemon Emerald is a Gen 3 game, but it is NOT a FireRed variant: its ROM
-- layout, its script bytecode addresses, its trainer table, its overworld
-- graphics ids, its map ids and its dialogue box all differ.  A "support" that
-- pointed the FRLG tables at an Emerald cart would not be support -- it would
-- be a wrong answer wearing the right shape, which is the exact failure the
-- brief forbids ("Emerald data must not be mistaken for FRLG data").
--
-- So Emerald gets its own namespace, its own detection, its own data table and
-- its own resolver, and FRLG keeps every byte of the behaviour it had.  Nothing
-- in this file is reachable from an FRLG boot: the caller in main.lua resolves
-- the game first and only calls in here when the answer is Emerald.
--
-- ---- what THIS build actually supports, stated honestly
--
-- The engine ships an Emerald import path, so an Emerald boot reaches a mod
-- with real Emerald data.  This module walks that data the same way the FRLG
-- side walks its own, but off its OWN table:
--
--   emerald/trainer_ids.lua   Emerald scriptKey -> Emerald trainer id
--   the engine's trainer pack  trainer id -> the cart's picture number
--   the engine's trainer pics  picture number -> the 64x64 portrait
--
-- The first is generated by .probe/dp3_emit_emerald_trainer_ids.lua from the
-- engine's own Emerald extraction; the second two come from the engine, read
-- through the same `src.core.game3` services the FRLG path uses.  The picture,
-- once found, is handed back in exactly the shape main.lua's picArt returns, so
-- the draw code does not know or care which game it came from.
--
-- What is deliberately NOT here, and why it is not a gap:
--
--   * no Emerald map_art / place_art table.  Those exist on the FRLG side to
--     disambiguate a SHARED GRAPHIC by the map it stands on, and the FRLG
--     graphics-id space is what they are keyed by.  Emerald's graphics ids are a
--     different space and the mod has no measured Emerald table for them; the
--     scriptKey route below is exact and needs no map fallback.  A bad map guess
--     would be a wrong face, so there is none.
--   * no Emerald crop table.  art/crops.lua's framings are keyed to FRLG picture
--     numbers.  The engine's own `TrainerPic.front` already returns the cart's
--     picture at its own size, and main.lua's draw path frames whatever it is
--     handed, so the picture is used as the cart cut it.
--
-- Both are stated as limitations rather than pretended away.  Tests in
-- tests/dp3_emerald_test.lua pin the contract either way: the resolver declines
-- with a non-empty, Emerald-naming reason rather than ever raising or falling
-- through to an FRLG table.

local Emerald = {}

-- ---- injected dependencies
--
-- A mod's files are loaded with `load()` inside the mod's sandbox, where the
-- ambient `require` may or may not be the engine's.  Rather than guess, the
-- caller in main.lua hands this module a `require`, a mod reader and a logger
-- once, and the module uses those.  All are optional: with none, every route
-- that needs the engine reports "unknown", which is the safe answer -- unknown
-- is not Emerald, and not Emerald is not FireRed.
--
-- `Emerald.bind{ require = ..., log = ..., read = ... }` is called by main.lua
-- right after the chunk loads.  It is idempotent, so a double call is harmless.
local _require = nil
local _log = nil
local _read = nil

function Emerald.bind(opts)
  opts = opts or {}
  if type(opts.require) == "function" then _require = opts.require end
  if type(opts.log) == "table" and type(opts.log.info) == "function" then
    _log = opts.log
  end
  if type(opts.read) == "function" then _read = opts.read end
  return Emerald
end

-- A require that never raises: returns the module or nil.
local function safeRequire(name)
  local req = _require or require
  local ok, value = pcall(req, name)
  if ok and type(value) == "table" then return value end
  return nil
end

-- The game ids this module owns.  `emerald` is the id the engine uses (matching
-- the lowercase style of `firered` / `leafgreen` in GameVersion.VERSIONS).  The
-- two alternates are defensive spellings an engine or a future manifest might
-- use; accepting them costs nothing and stops a real Emerald boot being mistaken
-- for FireRed over a spelling.
Emerald.GAME_IDS = { emerald = true, pokemonemerald = true, pokeemerald = true }

-- The cart we verified this build against.  Recorded so a diagnostic can say
-- which dump was seen, and so the tests can assert the detector accepts it.
--   title   : "POKEMON EMER"
--   gamecode: "BPEE"   (USA/Europe revision 0)
--   sha1    : f3ae088181bf583e55daf962a92bb46f4f1d07b7
Emerald.CART_GAMECODE = "BPEE"
Emerald.CART_SHA1 = "f3ae088181bf583e55daf962a92bb46f4f1d07b7"

-- Human-readable name for logs and menu copy, so nothing has to spell it twice.
Emerald.DISPLAY_NAME = "Pokemon Emerald"

-- Where the generated Emerald table lives, relative to the mod root.  One
-- literal, so the reader and the tests cannot drift apart.
Emerald.TRAINER_IDS_PATH = "emerald/trainer_ids.lua"

--- Is this game id an Emerald id?
--
-- Deliberately a pure function of the string so it can be unit-tested with no
-- engine at all, and so the caller has one place to ask.
function Emerald.isEmeraldId(id)
  return type(id) == "string" and Emerald.GAME_IDS[id:lower()] == true
end

--- The game id of the running process, or nil when the engine cannot say.
--
-- Two routes, in order of authority:
--
--   1. `GameVersion.get()` -- the engine's one source of truth for the active
--      version (src/core/GameVersion.lua).  This is what the importer, cache
--      mount and SaveData all read, so it is the answer that matters.
--   2. `Runtime._game` -- the live game3 service owner, which is what the mod
--      already reads in gameOf().  Used only when GameVersion is unavailable,
--      because a mod may be running under a sandbox that hides the module.
--
-- Returns the id as a string, or nil when neither route can answer.  A nil is
-- NOT Emerald and NOT FireRed -- the caller decides what an unknown game means;
-- this function only reports what it found.
function Emerald.detectGameId()
  local GameVersion = safeRequire("src.core.GameVersion")
  if GameVersion and GameVersion.get then
    local ok2, id = pcall(GameVersion.get)
    if ok2 and type(id) == "string" and id ~= "" then return id end
  end
  local Runtime = safeRequire("src.core.game3.runtime")
  if Runtime and type(Runtime._game) == "table" then
    local id = Runtime._game.gameId or Runtime._game.version or Runtime._game.id
    if type(id) == "string" and id ~= "" then return id end
  end
  return nil
end

--- Is the running game Emerald?
function Emerald.isRunning()
  return Emerald.isEmeraldId(Emerald.detectGameId())
end

-- ---- the diagnostic
--
-- One string per missing piece, built as data rather than assembled at each
-- call site so the tests can assert on the exact wording and a log line cannot
-- drift from the docs.
Emerald.MISSING_ENGINE_REASON =
  "this engine build has no Emerald import path, so no Emerald map objects, "
  .. "scripts or trainer pack can reach a mod"

Emerald.MISSING_TABLE_REASON =
  "the engine resolved Emerald, but " .. Emerald.TRAINER_IDS_PATH .. " is not "
  .. "in this build of the mod, so no Emerald script key can name a trainer"

Emerald.MISSING_PACK_REASON =
  "this Emerald boot has no trainer pack loaded yet, so an Emerald trainer id "
  .. "cannot be turned into the cart's picture number"

--- Why no portrait can be resolved on this Emerald boot, or nil when there IS
--- a reason to try.
--
-- Returning a reason is the SAFE answer: the caller draws a bare box, which is
-- what the game looks like with no portrait mod, rather than a wrong face.
--
-- The order mirrors the resolver: engine first, then the mod's own table, then
-- the engine's pack.  Each answer names the piece that is actually missing, so
-- a player or a bug report can tell "the engine is too old" apart from "the pack
-- has not been generated yet".
function Emerald.unsupportedReason()
  local GameVersion = safeRequire("src.core.GameVersion")
  if not (GameVersion and type(GameVersion.VERSIONS) == "table"
      and type(GameVersion.VERSIONS.emerald) == "table") then
    return Emerald.MISSING_ENGINE_REASON
  end
  if not Emerald.trainerIds() then return Emerald.MISSING_TABLE_REASON end
  return nil
end

-- ---- the Emerald trainer table
--
-- Read once, lazily, through the injected mod reader -- a mod's files are not on
-- package.path, so this is the same `mod:read` + `load` route main.lua uses for
-- art/trainer_ids.lua and art/crops.lua.  `false` records a failed attempt so a
-- missing table is not re-read on every box.
local _ids = nil

function Emerald.trainerIds()
  if _ids ~= nil then return _ids or nil end
  _ids = false
  if type(_read) ~= "function" then return nil end
  local ok, source = pcall(_read, Emerald.TRAINER_IDS_PATH)
  if ok and type(source) == "string" then
    local chunk = load(source, "@" .. Emerald.TRAINER_IDS_PATH)
    if chunk then
      local ok2, value = pcall(chunk)
      if ok2 and type(value) == "table" then _ids = value end
    end
  end
  if _log then
    if _ids then
      local n = 0
      for _ in pairs(_ids) do n = n + 1 end
      _log:info("emerald: loaded %s (%d entries)", Emerald.TRAINER_IDS_PATH, n)
    else
      _log:info("emerald: %s not available; %s", Emerald.TRAINER_IDS_PATH,
        Emerald.MISSING_TABLE_REASON)
    end
  end
  return _ids or nil
end

-- The trainer id for a speaker's script, or nil.  Pure table lookup, no engine
-- reach, so it can be tested with a stub table.
function Emerald.trainerIdFor(speaker)
  if type(speaker) ~= "table" then return nil end
  local explicit = tonumber(speaker.trainerId)
  if explicit and explicit > 0 then return explicit end
  local key = speaker.scriptKey
  if type(key) ~= "string" or key == "" then return nil end
  local ids = Emerald.trainerIds()
  if not ids then return nil end
  local tid = tonumber(ids[key])
  if tid and tid > 0 then return tid end
  return nil
end

-- The cart's picture number for a trainer id, read from the engine's own
-- Emerald trainer pack.  Same rule the FRLG side uses, and for the same reason:
-- picture 0 is the cart's NULL picture and `0` is truthy in Lua, so a lookup
-- that only asks "is there a number?" would hand every empty row the null
-- picture.  Class 0 means "not a trainer" and is likewise not a mapping.
--
-- The module is `src.core.game3.scripting.trainers` -- the SAME service
-- main.lua's FRLG path reads for its own id->picture leg, so the two games are
-- translated by one implementation and a change to it cannot drift apart from
-- itself.  The pack is keyed `trainers[id] = { class=, className=, pic=, name= }`.
function Emerald.picForTrainerId(tid)
  tid = tonumber(tid)
  if not tid or tid <= 0 then return nil end
  local pack = Emerald.trainerPack()
  if not pack then return nil end
  local row = type(pack.trainers) == "table" and pack.trainers[tid] or nil
  if type(row) ~= "table" then return nil end
  if tonumber(row.class) and tonumber(row.class) <= 0 then return nil end
  local pic = tonumber(row.pic)
  if pic and pic > 0 then return pic end
  return nil
end

--- The engine's trainer pack, or nil.  Exposed (and name-recorded) so a real
--- boot that cannot reach it says WHICH piece was unreachable rather than
--- looking like an empty table.  Cached only on success: the pack is a
--- generated cache, so a first ask that precedes it must be repeatable.
local _pack, _packErr = nil, nil

function Emerald.trainerPack()
  if _pack ~= nil then return _pack end
  local Trainers = safeRequire("src.core.game3.scripting.trainers")
  if not (Trainers and Trainers.pack) then
    _packErr = "src.core.game3.scripting.trainers is not reachable from this mod"
    return nil
  end
  local ok, pack = pcall(Trainers.pack)
  if not ok or type(pack) ~= "table" then
    _packErr = "the engine's trainer pack is not generated for this boot yet"
    return nil
  end
  _pack, _packErr = pack, nil
  return _pack
end

--- Why the pack could not be read, for a diagnostic; nil when it could.
function Emerald.trainerPackError() return _packErr end

-- The portrait for a picture number, in exactly the shape main.lua's picArt
-- returns: `{ image = <Image>, w = <number>, h = <number>, pic = <number> }`,
-- or nil.  Read through the engine's trainer-pic service, which is what turns a
-- cart picture id into a texture; it is pcall'd because a headless or
-- half-initialised boot must not turn a portrait lookup into an error.
function Emerald.artForPic(pic)
  pic = tonumber(pic)
  if not pic or pic <= 0 then return nil end
  local TrainerPic = safeRequire("src.core.game3.trainer_pic")
  if not (TrainerPic and TrainerPic.front) then return nil end
  local ok, entry = pcall(TrainerPic.front, pic)
  if ok and type(entry) == "table" and entry.image then
    return { image = entry.image, w = entry.w, h = entry.h, pic = pic }
  end
  return nil
end

--- Resolve a portrait for an Emerald speaker.
--
-- The Emerald counterpart of main.lua's FRLG `artFor`, and a much shorter one,
-- because the only route it needs is the exact one: the object's scriptKey names
-- its trainer, and the cart's row for that id names the picture.  There is no
-- graphics-id fallback and no map fallback here -- both are FRLG tables and
-- neither would be right on an Emerald cart (see the header).
--
-- Returns `art` on success, or `nil, reason` when it cannot.  It never raises,
-- and it never consults an FRLG table.
--
-- THE GAME CHECK IS PART OF THE RESOLVER, not left to the caller.  `opts.force`
-- exists for a caller that has already asked `isRunning()` itself -- main.lua
-- does exactly that, one branch above -- but the DEFAULT is to refuse on a boot
-- that is not Emerald.  That is deliberate: the brief's rule is that Emerald
-- data must never stand in for FRLG data, and a resolver that answered whenever
-- its own tables happened to be loadable would make that rule a property of
-- every call site rather than of this module -- one wiring mistake away from an
-- Emerald face on a FireRed cart.  A non-Emerald boot therefore gets `nil` with
-- no reason string, because nothing is missing: this is simply not our game,
-- and the FRLG path is the one that should answer.
function Emerald.artFor(speaker, opts)
  if type(speaker) ~= "table" then return nil, Emerald.unsupportedReason() end

  if not (type(opts) == "table" and opts.force) and not Emerald.isRunning() then
    return nil
  end

  local reason = Emerald.unsupportedReason()
  if reason then return nil, reason end

  local tid = Emerald.trainerIdFor(speaker)
  if not tid then
    -- Not an error: most objects are not trainers.  This is the ordinary
    -- "no portrait for this person" answer, the same one the FRLG path gives
    -- when every route declines -- so it carries no reason string.
    return nil
  end

  local pic = Emerald.picForTrainerId(tid)
  if not pic then
    return nil, Emerald.trainerPackError() or Emerald.MISSING_PACK_REASON
  end

  local art = Emerald.artForPic(pic)
  if art then return art end
  return nil, ("Emerald trainer %d wants picture %d, which this boot cannot read")
    :format(tid, pic)
end

--- Would Emerald portraits be drawn at all this boot?  True only when the engine
--- can resolve Emerald AND the mod has its Emerald table.  A single predicate so
--- the caller has one place to branch rather than re-deriving the rule.
function Emerald.canDrawPortraits()
  return Emerald.isRunning() and Emerald.unsupportedReason() == nil
end

return Emerald
