-- Emerald support for Dialogue Portraits (Gen 3).
--
-- ---- why this file exists, and why it is a separate tree
--
-- Everything else in this repository is FireRed / LeafGreen.  The mod's own
-- header says so, and every data table it ships -- art/trainer_ids.lua,
-- art/map_art.lua, art/crops.lua, the GFX_ART / SPRITE_ART tables in main.lua --
-- is keyed to facts that only exist IN THOSE TWO CARTS:
--
--   * the ScriptKey `g3:XXXXXXXX` the FRLG importer stamps on every map object;
--   * the FRLG graphics-id space (GFX_ART[25] = 103, and so on);
--   * the FRLG map-id spelling (FR_ROUTE_24, ...);
--   * the FRLG trainer CLASS vs trainer PIC number spaces, which are two
--     different spaces in FRLG and a third, different thing in Emerald;
--   * the 240x160 FireRed message box and the FireRed latin_normal font, both
--     of which the mod's seams (src.ui.game3.message / chrome / frlg_font) are.
--
-- Pokemon Emerald is a Gen 3 game, but it is NOT a FireRed variant: its ROM
-- layout, its script bytecode addresses, its trainer table, its overworld
-- graphics ids, its map ids and its dialogue box all differ.  A "support" that
-- pointed the FRLG tables at an Emerald cart would not be support -- it would
-- be a wrong answer wearing the right shape, which is the exact failure the
-- brief forbids ("Emerald data must not be mistaken for FRLG data").
--
-- So Emerald gets its own namespace, its own detection, its own data table and
-- its own resolver, and FRLG keeps every byte of the behaviour it had.  Nothing
-- in this file is reachable from an FRLG boot: the caller in main.lua resolves
-- the game first and only calls in here when the answer is Emerald.
--
-- ---- what THIS build actually supports, stated honestly
--
-- The engine ships an Emerald import path, so an Emerald boot reaches a mod
-- with real Emerald data.  This module walks that data the same way the FRLG
-- side walks its own, but off its OWN tables:
--
--   emerald/trainer_ids.lua   Emerald scriptKey -> Emerald trainer id
--   emerald/gfx_art.lua       Emerald graphics id -> the picture it means
--   emerald/map_art.lua       (Emerald map id, graphics id) -> the picture
--   emerald/gfx_names.lua     Emerald graphics id -> the cart's name for it
--   the engine's trainer pack  trainer id -> class, name and picture
--   the engine's trainer pics  picture number -> the 64x64 portrait
--
-- The first four are generated by .probe/dp3_emit_emerald_*.lua from the
-- engine's own Emerald extraction of the player's ROM; the last two come from
-- the engine, read through the same `src.core.game3` services the FRLG path
-- uses.  The picture, once found, is handed back in exactly the shape main.lua's
-- picArt returns, so the draw code does not know or care which game it came from.
--
-- ---- the four routes, and their order (the FRLG cascade, in Emerald dress)
--
-- The FIRST build of this module (1.3.2) implemented only route 1, and the
-- report was exactly what that predicts: "the mod loads, but not working. no
-- portraits has been showing during dialogue boxs."  Of the 2,941 objects the
-- engine places in Emerald only 588 are trainers an id can name, so 2,353
-- ordinary people resolved to nil and the caller drew a bare box.  The routes
-- are the same cascade main.lua runs for FRLG, made from Emerald facts:
--
--   1. the OBJECT's scriptKey names a TRAINER  -> that trainer's own picture.
--      Exact, and it outranks everything: an id is a person, a graphic is a
--      uniform (see emerald/trainer_ids.lua and gfx_art.lua's header).
--   2. the NAME the box says is a trainer's own name -> that trainer's picture.
--      Refused when two pictures share the name, so a generic "GRUNT" cannot
--      hand every grunt the admin's face -- the same rule as FRLG's picForName.
--   3. the object's own CLASS -> the class's picture.  Read off the object's
--      graphic's cart name, so it answers only when that name IS a class name.
--   4. the HAND-AUTHORED person table (emerald/gfx_art_people.lua): an exact
--      picture for a graphic no trainer wears, or a deliberate decline.  Runs
--      before the two statistical tables because a decision about this graphic
--      beats a majority over the ROM.
--   5. the (MAP, GRAPHIC) pair -> the picture the majority of THIS map's
--      trainers wearing that graphic have (emerald/map_art.lua).
--   6. the GRAPHIC alone -> the picture the majority of the whole ROM's
--      trainers wearing it have (emerald/gfx_art.lua).
--
-- Routes 5 and 6 are the ones that matter for the report, because the two and a
-- half thousand ordinary people have neither an id nor a name: their graphic is
-- the only fact about them, and it is what the cart dressed them in.  Route 4 is
-- what answers the people not one trainer wears -- the townsfolk, the nurse, the
-- gym leaders -- and what declines, honestly, the few the cart never drew.
--
-- ---- what is deliberately NOT here, and why it is not a gap
--
--   * no Emerald crop table.  art/crops.lua's framings are keyed to FRLG picture
--     numbers.  The engine's own `TrainerPic.front` already returns the cart's
--     picture at its own size, and main.lua's draw path frames whatever it is
--     handed, so the picture is used as the cart cut it.
--   * no FRLG fallback of ANY kind.  Every table this module reads is an
--     Emerald table keyed by Emerald facts, and the resolver refuses on a
--     non-Emerald boot by default.  A wrong face is worse than none, and an
--     FRLG face on an Emerald cart is the wrongest of all.
--
-- The gap that REMAINS, stated rather than pretended away: Emerald's overworld
-- art is a SEPARATE set from its trainer busts, so a graphic worn by no trainer
-- (and named by no class) has no measured answer and gets NO portrait -- which
-- is this mod's rule everywhere the data does not decide.  Routes 4 and 5 cover
-- 69 of the 166 used person graphics; the rest are the anonymous kinds the cart
-- never drew a battle bust of.  Tests in tests/dp3_emerald_test.lua pin the
-- contract either way: the resolver declines with a non-empty, Emerald-naming
-- reason rather than ever raising or falling through to an FRLG table.

local Emerald = {}

-- ---- injected dependencies
--
-- A mod's files are loaded with `load()` inside the mod's sandbox, where the
-- ambient `require` may or may not be the engine's.  Rather than guess, the
-- caller in main.lua hands this module a `require`, a mod reader and a logger
-- once, and the module uses those.  All are optional: with none, every route
-- that needs the engine reports "unknown", which is the safe answer -- unknown
-- is not Emerald, and not Emerald is not FireRed.
--
-- `Emerald.bind{ require = ..., log = ..., read = ... }` is called by main.lua
-- right after the chunk loads.  It is idempotent, so a double call is harmless.
local _require = nil
local _log = nil
local _read = nil

function Emerald.bind(opts)
  opts = opts or {}
  if type(opts.require) == "function" then _require = opts.require end
  if type(opts.log) == "table" and type(opts.log.info) == "function" then
    _log = opts.log
  end
  if type(opts.read) == "function" then _read = opts.read end
  return Emerald
end

-- A require that never raises: returns the module or nil.
local function safeRequire(name)
  local req = _require or require
  local ok, value = pcall(req, name)
  if ok and type(value) == "table" then return value end
  return nil
end

-- The game ids this module owns.  `emerald` is the id the engine uses (matching
-- the lowercase style of `firered` / `leafgreen` in GameVersion.VERSIONS).  The
-- two alternates are defensive spellings an engine or a future manifest might
-- use; accepting them costs nothing and stops a real Emerald boot being mistaken
-- for FireRed over a spelling.
Emerald.GAME_IDS = { emerald = true, pokemonemerald = true, pokeemerald = true }

-- The cart we verified this build against.  Recorded so a diagnostic can say
-- which dump was seen, and so the tests can assert the detector accepts it.
--   title   : "POKEMON EMER"
--   gamecode: "BPEE"   (USA/Europe revision 0)
--   sha1    : f3ae088181bf583e55daf962a92bb46f4f1d07b7
Emerald.CART_GAMECODE = "BPEE"
Emerald.CART_SHA1 = "f3ae088181bf583e55daf962a92bb46f4f1d07b7"

-- Human-readable name for logs and menu copy, so nothing has to spell it twice.
Emerald.DISPLAY_NAME = "Pokemon Emerald"

-- Where the generated Emerald tables live, relative to the mod root.  One
-- literal each, so the readers and the tests cannot drift apart.
Emerald.TRAINER_IDS_PATH = "emerald/trainer_ids.lua"
Emerald.GFX_ART_PATH    = "emerald/gfx_art.lua"
Emerald.MAP_ART_PATH    = "emerald/map_art.lua"
Emerald.GFX_NAMES_PATH  = "emerald/gfx_names.lua"
Emerald.PEOPLE_PATH     = "emerald/gfx_art_people.lua"

--- Is this game id an Emerald id?
--
-- Deliberately a pure function of the string so it can be unit-tested with no
-- engine at all, and so the caller has one place to ask.
function Emerald.isEmeraldId(id)
  return type(id) == "string" and Emerald.GAME_IDS[id:lower()] == true
end

--- The game id of the running process, or nil when the engine cannot say.
--
-- Two routes, in order of authority:
--
--   1. `GameVersion.get()` -- the engine's one source of truth for the active
--      version (src/core/GameVersion.lua).  This is what the importer, cache
--      mount and SaveData all read, so it is the answer that matters.
--   2. `Runtime._game` -- the live game3 service owner, which is what the mod
--      already reads in gameOf().  Used only when GameVersion is unavailable,
--      because a mod may be running under a sandbox that hides the module.
--
-- Returns the id as a string, or nil when neither route can answer.  A nil is
-- NOT Emerald and NOT FireRed -- the caller decides what an unknown game means;
-- this function only reports what it found.
function Emerald.detectGameId()
  local GameVersion = safeRequire("src.core.GameVersion")
  if GameVersion and GameVersion.get then
    local ok2, id = pcall(GameVersion.get)
    if ok2 and type(id) == "string" and id ~= "" then return id end
  end
  local Runtime = safeRequire("src.core.game3.runtime")
  if Runtime and type(Runtime._game) == "table" then
    local id = Runtime._game.gameId or Runtime._game.version or Runtime._game.id
    if type(id) == "string" and id ~= "" then return id end
  end
  return nil
end

--- Is the running game Emerald?
function Emerald.isRunning()
  return Emerald.isEmeraldId(Emerald.detectGameId())
end

-- ---- the diagnostic
--
-- One string per missing piece, built as data rather than assembled at each
-- call site so the tests can assert on the exact wording and a log line cannot
-- drift from the docs.
Emerald.MISSING_ENGINE_REASON =
  "this engine build has no Emerald import path, so no Emerald map objects, "
  .. "scripts or trainer pack can reach a mod"

Emerald.MISSING_TABLE_REASON =
  "the engine resolved Emerald, but " .. Emerald.TRAINER_IDS_PATH .. " is not "
  .. "in this build of the mod, so no Emerald script key can name a trainer"

Emerald.MISSING_PACK_REASON =
  "this Emerald boot has no trainer pack loaded yet, so an Emerald trainer id "
  .. "cannot be turned into the cart's picture number"

--- Why no portrait can be resolved on this Emerald boot, or nil when there IS
--- a reason to try.
--
-- Returning a reason is the SAFE answer: the caller draws a bare box, which is
-- what the game looks like with no portrait mod, rather than a wrong face.
--
-- The order mirrors the resolver: engine first, then the mod's own table, then
-- the engine's pack.  Each answer names the piece that is actually missing, so
-- a player or a bug report can tell "the engine is too old" apart from "the pack
-- has not been generated yet".
function Emerald.unsupportedReason()
  local GameVersion = safeRequire("src.core.GameVersion")
  if not (GameVersion and type(GameVersion.VERSIONS) == "table"
      and type(GameVersion.VERSIONS.emerald) == "table") then
    return Emerald.MISSING_ENGINE_REASON
  end
  if not Emerald.trainerIds() then return Emerald.MISSING_TABLE_REASON end
  return nil
end

-- ---- the Emerald trainer table
--
-- Read once, lazily, through the injected mod reader -- a mod's files are not on
-- package.path, so this is the same `mod:read` + `load` route main.lua uses for
-- art/trainer_ids.lua and art/crops.lua.  `false` records a failed attempt so a
-- missing table is not re-read on every box.
local _ids = nil

function Emerald.trainerIds()
  if _ids ~= nil then return _ids or nil end
  _ids = false
  if type(_read) ~= "function" then return nil end
  local ok, source = pcall(_read, Emerald.TRAINER_IDS_PATH)
  if ok and type(source) == "string" then
    local chunk = load(source, "@" .. Emerald.TRAINER_IDS_PATH)
    if chunk then
      local ok2, value = pcall(chunk)
      if ok2 and type(value) == "table" then _ids = value end
    end
  end
  if _log then
    if _ids then
      local n = 0
      for _ in pairs(_ids) do n = n + 1 end
      _log:info("emerald: loaded %s (%d entries)", Emerald.TRAINER_IDS_PATH, n)
    else
      _log:info("emerald: %s not available; %s", Emerald.TRAINER_IDS_PATH,
        Emerald.MISSING_TABLE_REASON)
    end
  end
  return _ids or nil
end

-- ---- the generated Emerald data tables
--
-- Same reader as trainerIds, generalised: a mod's files are not on
-- package.path, so each is read through the injected `_read` and `load`ed, and a
-- failure is remembered so a missing table is not re-read on every box.  A table
-- that is absent is NOT an error -- an older build of the mod simply has no
-- answer for the routes it feeds, and on a real Emerald boot that is a bare box,
-- never a crash.
local _tables = {}

local function loadTable(path)
  if _tables[path] ~= nil then return _tables[path] or nil end
  _tables[path] = false
  if type(_read) ~= "function" then return nil end
  local ok, source = pcall(_read, path)
  if ok and type(source) == "string" then
    local chunk = load(source, "@" .. path)
    if chunk then
      local ok2, value = pcall(chunk)
      if ok2 and type(value) == "table" then _tables[path] = value end
    end
  end
  if _log then
    if _tables[path] then
      local n = 0
      for _ in pairs(_tables[path]) do n = n + 1 end
      _log:info("emerald: loaded %s (%d entries)", path, n)
    else
      _log:info("emerald: %s not available", path)
    end
  end
  return _tables[path] or nil
end

--- Emerald graphics id -> the picture it means (emerald/gfx_art.lua), or nil.
-- Keyed by the cart's graphics number, values are front-picture ids.
function Emerald.gfxArt()   return loadTable(Emerald.GFX_ART_PATH)   end
--- (Emerald map id, graphics id) -> picture (emerald/map_art.lua), or nil.
function Emerald.mapArt()   return loadTable(Emerald.MAP_ART_PATH)   end
--- Emerald graphics id -> the cart's name for it (emerald/gfx_names.lua), or nil.
function Emerald.gfxNames() return loadTable(Emerald.GFX_NAMES_PATH) end
--- Emerald graphics id -> an EXACT picture, or `false` to decline the graphic
--- (emerald/gfx_art_people.lua).  Hand-authored, so it OUTRANKS the generated
--- majorities -- see the file's header for why and how its values were decided.
function Emerald.peopleArt() return loadTable(Emerald.PEOPLE_PATH) end

-- The trainer id for a speaker's script, or nil.  Pure table lookup, no engine
-- reach, so it can be tested with a stub table.
function Emerald.trainerIdFor(speaker)
  if type(speaker) ~= "table" then return nil end
  local explicit = tonumber(speaker.trainerId)
  if explicit and explicit > 0 then return explicit end
  local key = speaker.scriptKey
  if type(key) ~= "string" or key == "" then return nil end
  local ids = Emerald.trainerIds()
  if not ids then return nil end
  local tid = tonumber(ids[key])
  if tid and tid > 0 then return tid end
  return nil
end

-- The cart's picture number for a trainer id, read from the engine's own
-- Emerald trainer pack.
--
-- ---- THE GUARD IS `pic >= 0`, NOT `pic > 0`, AND THAT IS EMERALD-SPECIFIC
--
-- The FRLG side refuses picture 0 because FRLG's picture 0 is its NULL picture:
-- every row the cart left empty carries it, and `0` is truthy in Lua, so a
-- lookup that only asked "is there a number?" would hand every empty row a blank
-- face.  EMERALD IS NOT FRLG, and copying that rule onto it was this module's
-- second defect.
--
-- In Emerald picture 0 is a REAL picture: the HIKER bust, worn by the class-2
-- HIKER (trainer 1 SAWYER and 43 others) -- measured by .probe/dp3_emerald_pics.lua
-- against the player's own ROM.  Emerald marks "no picture" with NEGATIVE
-- sentinels, not with 0, so 0 is an ordinary id here and refusing it silently
-- stripped the face from every Hiker in Hoenn.  The guard is therefore
-- `pic >= 0`, and the ONLY value that is "no picture" is one that is absent or
-- negative -- which is what `TrainerPic.front` itself enforces (`picId < 0`).
--
-- Class 0 still means "not a trainer" and is not a mapping: that part of the
-- FRLG rule is about the CLASS space, and the class spaces do agree on it.
--
-- The module is `src.core.game3.scripting.trainers` -- the SAME service
-- main.lua's FRLG path reads for its own id->picture leg, so the two games are
-- translated by one implementation and a change to it cannot drift apart from
-- itself.  The pack is keyed `trainers[id] = { class=, className=, pic=, name= }`.
function Emerald.picForTrainerId(tid)
  tid = tonumber(tid)
  if not tid or tid <= 0 then return nil end
  local pack = Emerald.trainerPack()
  if not pack then return nil end
  local row = type(pack.trainers) == "table" and pack.trainers[tid] or nil
  if type(row) ~= "table" then return nil end
  if tonumber(row.class) and tonumber(row.class) <= 0 then return nil end
  local pic = tonumber(row.pic)
  if pic and pic >= 0 then return pic end
  return nil
end

--- The engine's trainer pack, or nil.  Exposed (and name-recorded) so a real
--- boot that cannot reach it says WHICH piece was unreachable rather than
--- looking like an empty table.  Cached only on success: the pack is a
--- generated cache, so a first ask that precedes it must be repeatable.
local _pack, _packErr = nil, nil

function Emerald.trainerPack()
  if _pack ~= nil then return _pack end
  local Trainers = safeRequire("src.core.game3.scripting.trainers")
  if not (Trainers and Trainers.pack) then
    _packErr = "src.core.game3.scripting.trainers is not reachable from this mod"
    return nil
  end
  local ok, pack = pcall(Trainers.pack)
  if not ok or type(pack) ~= "table" then
    _packErr = "the engine's trainer pack is not generated for this boot yet"
    return nil
  end
  _pack, _packErr = pack, nil
  return _pack
end

--- Why the pack could not be read, for a diagnostic; nil when it could.
function Emerald.trainerPackError() return _packErr end

-- ---- the pack index: class -> picture, name -> picture
--
-- The Emerald counterpart of main.lua's loadPackIndex, built from the same
-- pack.  Two maps, both decided by the cart's own rows:
--
--   byClass[classId]  = the picture the class pins, or the most common of the
--                       ones it pins (Emerald's LEADER class holds every gym
--                       leader, so a class alone cannot tell them apart -- the
--                       graphic does, and route 4/5 is what separates them).
--   byName[name]      = a trainer's own picture, or `false` when two pictures
--                       share the name.  `false` is "ambiguous" as against
--                       nil's "unknown": a name that does not name anybody in
--                       particular must not answer, or a generic "GRUNT" would
--                       hand every grunt the admin's face.
--
-- Built lazily and cached, because it walks 855 rows.  A missing pack yields an
-- index of empty maps rather than nil, so the callers stay branch-free.
local _index = nil

function Emerald.packIndex()
  if _index then return _index end
  local index = { byClass = {}, byName = {}, classNames = {}, classRows = {} }
  _index = index
  local pack = Emerald.trainerPack()
  if not pack then return index end

  local classNames = pack.classNames
  if type(classNames) == "table" then
    for id, name in pairs(classNames) do
      local cid = tonumber(id)
      if cid and type(name) == "string" and name ~= "" then
        index.classNames[cid] = name:upper()
      end
    end
  end

  local classCount = {}   -- class id -> picture -> rows
  for _, row in pairs(type(pack.trainers) == "table" and pack.trainers or {}) do
    if type(row) == "table" then
      local cls  = tonumber(row.class)
      local pic  = tonumber(row.pic)
      -- pic >= 0, not > 0: Emerald's 0 is the Hiker's real picture (see
      -- picForTrainerId for the measurement and the reasoning).
      if pic and pic >= 0 then
        if cls and cls > 0 then
          local slot = classCount[cls]
          if not slot then slot = {}; classCount[cls] = slot end
          slot[pic] = (slot[pic] or 0) + 1
        end
        local name = row.name
        if type(name) == "string" and name ~= "" then
          local key = name:upper()
          local known = index.byName[key]
          if known == nil then
            index.byName[key] = pic
          elseif known ~= pic then
            -- Two pictures under one name: it names nobody in particular.
            index.byName[key] = false
          end
        end
      end
      if cls and cls > 0 then
        index.classRows[cls] = (index.classRows[cls] or 0) + 1
      end
    end
  end

  -- The class's picture: the one the most rows wear, ties to the lower id so
  -- the answer is stable across runs (pairs() order is not).
  for cls, counts in pairs(classCount) do
    local bestPic, bestN
    for pic, n in pairs(counts) do
      if bestN == nil or n > bestN or (n == bestN and pic < bestPic) then
        bestPic, bestN = pic, n
      end
    end
    index.byClass[cls] = bestPic
  end

  return index
end

-- Class id -> front-pic id, through the pack.  Exact when the class pins one
-- picture; the most common of them when it pins several.
function Emerald.picForClass(classId)
  classId = tonumber(classId)
  if not classId then return nil end
  return Emerald.packIndex().byClass[classId]
end

-- Class NAME -> class id, so a graphic's cart name can be tried as a class name
-- the way FRLG's classIdForName does.  Emerald's class table has no duplicated
-- names (measured: 66 classes, 66 distinct uppercased names), so the plain
-- inverse is exact and needs no row-count tie-break.
function Emerald.classIdForName(name)
  if type(name) ~= "string" or name == "" then return nil end
  local key = name:upper()
  local names = Emerald.packIndex().classNames
  for cid, n in pairs(names) do
    if n == key then return cid end
  end
  return nil
end

-- A trainer's own name -> front-pic id.  nil when the name is unknown OR worn
-- by two different pictures -- see packIndex.
function Emerald.picForName(name)
  if type(name) ~= "string" or name == "" then return nil end
  local pic = Emerald.packIndex().byName[name:upper()]
  if pic == false then return nil end
  return pic
end

-- The portrait for a picture number, in exactly the shape main.lua's picArt
-- returns: `{ image = <Image>, w = <number>, h = <number>, pic = <number> }`,
-- or nil.  Read through the engine's trainer-pic service, which is what turns a
-- cart picture id into a texture; it is pcall'd because a headless or
-- half-initialised boot must not turn a portrait lookup into an error.
--
-- `pic < 0` is the only refusal: the engine's own TrainerPic.front takes any id
-- >= 0 (picture 0 is the Hiker), and a negative id is Emerald's "no picture"
-- sentinel.  Refusing 0 here would re-introduce the defect this module fixed.
function Emerald.artForPic(pic)
  pic = tonumber(pic)
  if not pic or pic < 0 then return nil end
  local TrainerPic = safeRequire("src.core.game3.trainer_pic")
  if not (TrainerPic and TrainerPic.front) then return nil end
  local ok, entry = pcall(TrainerPic.front, pic)
  if ok and type(entry) == "table" and entry.image then
    return { image = entry.image, w = entry.w, h = entry.h, pic = pic }
  end
  return nil
end

--- Resolve a portrait for an Emerald speaker.
--
-- The Emerald counterpart of main.lua's FRLG `artFor`, running the same four
-- routes in the same order, made from Emerald facts:
--
--   1. scriptKey -> trainer id -> that trainer's picture.  Exact.
--   2. the box's own NAME -> that trainer's picture (ambiguous names refused).
--   3. the graphics id's cart NAME -> a class -> the class's picture.  This is
--      the step FRLG calls the class route, and it is why a Hiker, a Lass or a
--      Beauty gets the right bust from the graphic alone: the cart's name for
--      gfx 55 IS "HIKER".
--   4. the (map, graphics) pair -> the picture this map's trainers wearing that
--      graphic have in the majority (emerald/map_art.lua).
--   5. the graphics id alone -> the picture the whole ROM's trainers wearing it
--      have in the majority (emerald/gfx_art.lua).
--
-- 4 and 5 are what answer the 2,353 ordinary people routes 1-3 cannot name, and
-- they are the fix for the report ("no portraits has been showing").  Each is a
-- MEASURED majority over the cart's own rows, so it can be wrong for a minority
-- by construction -- exactly FRLG's GFX_ART trade-off, and better than a bare
-- box for everybody.
--
-- Returns `art` on success, or `nil, reason` when it cannot.  It never raises,
-- and it never consults an FRLG table.
--
-- THE GAME CHECK IS PART OF THE RESOLVER, not left to the caller.  `opts.force`
-- exists for a caller that has already asked `isRunning()` itself -- main.lua
-- does exactly that, one branch above -- but the DEFAULT is to refuse on a boot
-- that is not Emerald.  That is deliberate: the brief's rule is that Emerald
-- data must never stand in for FRLG data, and a resolver that answered whenever
-- its own tables happened to be loadable would make that rule a property of
-- every call site rather than of this module -- one wiring mistake away from an
-- Emerald face on a FireRed cart.  A non-Emerald boot therefore gets `nil` with
-- no reason string, because nothing is missing: this is simply not our game,
-- and the FRLG path is the one that should answer.
function Emerald.artFor(speaker, opts)
  if type(speaker) ~= "table" then return nil, Emerald.unsupportedReason() end

  if not (type(opts) == "table" and opts.force) and not Emerald.isRunning() then
    return nil
  end

  local reason = Emerald.unsupportedReason()
  if reason then return nil, reason end

  local function viaPic(pic)
    if pic == nil or pic == false then return nil end
    return Emerald.artForPic(pic)
  end

  -- 1. the OBJECT's scriptKey -> its trainer -> its picture.
  local tid = Emerald.trainerIdFor(speaker)
  if tid then
    local art = viaPic(Emerald.picForTrainerId(tid))
    if art then return art end
    -- The id was known but the pack could not turn it into a picture: that is a
    -- real diagnostic, not an ordinary "no portrait".  Fall through to the
    -- routes below first -- a graphic answer is better than none -- and only
    -- report the pack failure if nothing else answers.
  end

  -- 2. the box's own NAME -> that trainer's picture.  Step 1 outranks it (an id
  --    is a person, a name can be shared), which is why it is asked second.
  local nameArt = viaPic(Emerald.picForName(speaker.name))
  if nameArt then return nameArt end

  -- 3. the graphics id's cart name -> a class -> the class's picture.
  local gfx = tonumber(speaker.gfx)
  local gfxName
  if gfx then
    local names = Emerald.gfxNames()
    gfxName = names and names[gfx] or nil
    if type(gfxName) == "string" and gfxName ~= "" then
      local classArt = viaPic(Emerald.picForClass(Emerald.classIdForName(gfxName)))
      if classArt then return classArt end
    end
  end

  -- 4. the HAND-AUTHORED person table.  It runs BEFORE the two generated
  --    majorities because a hand entry is a decision about THIS graphic, and the
  --    majorities are statistical answers that are wrong for a minority by
  --    construction.  It is what answers the 25 kinds whose graphic no trainer
  --    wears -- the townsfolk, the nurse, the leaders -- and its `false` is a
  --    real decline (a person the cart drew no bust of), so it stops the routes
  --    below rather than falling through to a majority that would put a wrong
  --    face on a shop clerk.
  if gfx then
    local people = Emerald.peopleArt()
    if type(people) == "table" then
      local peoplePic = people[gfx]
      if peoplePic == false then return nil end
      local peopleArt = viaPic(peoplePic)
      if peopleArt then return peopleArt end
    end
  end

  -- 5. the (map, graphics) pair.  A map is more specific than the whole ROM, so
  --    this runs before the graphic-alone route.
  if gfx then
    local mapId = speaker.mapId
    if type(mapId) == "string" and mapId ~= "" then
      local maps = Emerald.mapArt()
      local onMap = maps and maps[mapId]
      if type(onMap) == "table" then
        local mapPic = onMap[gfx]
        if mapPic == false then return nil end   -- declined on this map
        local mapArt = viaPic(mapPic)
        if mapArt then return mapArt end
      end
    end
  end

  -- 6. the graphics id alone -- the whole-ROM majority.  LAST, because it is the
  --    least specific fact about the person.
  if gfx then
    local gfxArtTbl = Emerald.gfxArt()
    if gfxArtTbl then
      local gfxPic = gfxArtTbl[gfx]
      if gfxPic == false then return nil end   -- declined for the graphic itself
      local gfxArt = viaPic(gfxPic)
      if gfxArt then return gfxArt end
    end
  end

  -- Nothing answered.  Report the pack failure only if the failure was about a
  -- trainer we DID identify (an id route that had a row but no readable
  -- picture); otherwise this is the ordinary "the cart never drew this person",
  -- which carries no reason string, exactly as the FRLG path declines silently.
  if tid and not Emerald.picForTrainerId(tid) then
    return nil, Emerald.trainerPackError() or Emerald.MISSING_PACK_REASON
  end
  return nil
end

--- Would Emerald portraits be drawn at all this boot?  True only when the engine
--- can resolve Emerald AND the mod has its Emerald table.  A single predicate so
--- the caller has one place to branch rather than re-deriving the rule.
function Emerald.canDrawPortraits()
  return Emerald.isRunning() and Emerald.unsupportedReason() == nil
end

return Emerald
