-- Emerald support for Dialogue Portraits (Gen 3).
--
-- ---- why this file exists, and why it is a separate tree
--
-- Everything else in this repository is FireRed / LeafGreen.  The mod's own
-- header says so, and every data table it ships -- art/trainer_ids.lua,
-- art/map_art.lua, art/crops.lua, the GFX_ART / SPRITE_ART tables in main.lua --
-- is keyed to facts that only exist IN THOSE TWO CARTS:
--
--   * the ScriptKey `g3:XXXXXXXX` the FRLG importer stamps on every map object;
--   * the FRLG graphics-id space (GFX_ART[25] = 103, and so on);
--   * the FRLG map-id spelling (FR_ROUTE_24, ...);
--   * the FRLG trainer CLASS vs trainer PIC number spaces, which are two
--     different spaces in FRLG and a third, different thing in Emerald;
--   * the 240x160 FireRed message box and the FireRed latin_normal font, both
--     of which the mod's seams (src.ui.game3.message / chrome / frlg_font) are.
--
-- Pokemon Emerald is a Gen 3 game, but it is NOT a FireRed variant: its ROM
-- layout, its script bytecode addresses, its trainer table, its overworld
-- graphics ids, its map ids and its dialogue box all differ.  A "support" that
-- pointed the FRLG tables at an Emerald cart would not be support -- it would
-- be a wrong answer wearing the right shape, which is the exact failure the
-- brief forbids ("Emerald data must not be mistaken for FRLG data").
--
-- So Emerald gets its own namespace, its own detection, its own data table and
-- its own resolver, and FRLG keeps every byte of the behaviour it had.  Nothing
-- in this file is reachable from an FRLG boot: the caller in main.lua resolves
-- the game first and only calls in here when the answer is Emerald.
--
-- ---- what THIS build actually supports, stated honestly
--
-- The engine ships an Emerald import path, so an Emerald boot reaches a mod
-- with real Emerald data.  This module walks that data the same way the FRLG
-- side walks its own, but off its OWN tables:
--
--   emerald/trainer_ids.lua   Emerald scriptKey -> Emerald trainer id
--   emerald/gfx_art.lua       Emerald graphics id -> the picture it means
--   emerald/map_art.lua       (Emerald map id, graphics id) -> the picture
--   emerald/gfx_names.lua     Emerald graphics id -> the cart's name for it
--   the engine's trainer pack  trainer id -> class, name and picture
--   the engine's trainer pics  picture number -> the 64x64 portrait
--
-- The first four are generated by .probe/dp3_emit_emerald_*.lua from the
-- engine's own Emerald extraction of the player's ROM; the last two come from
-- the engine, read through the same `src.core.game3` services the FRLG path
-- uses.  The picture, once found, is handed back in exactly the shape main.lua's
-- picArt returns, so the draw code does not know or care which game it came from.
--
-- ---- the four routes, and their order (the FRLG cascade, in Emerald dress)
--
-- The FIRST build of this module (1.3.2) implemented only route 1, and the
-- report was exactly what that predicts: "the mod loads, but not working. no
-- portraits has been showing during dialogue boxs."  Of the 2,941 objects the
-- engine places in Emerald only 588 are trainers an id can name, so 2,353
-- ordinary people resolved to nil and the caller drew a bare box.  The routes
-- are the same cascade main.lua runs for FRLG, made from Emerald facts:
--
--   1. the OBJECT's scriptKey names a TRAINER  -> that trainer's own picture.
--      Exact, and it outranks everything: an id is a person, a graphic is a
--      uniform (see emerald/trainer_ids.lua and gfx_art.lua's header).
--   2. the NAME the box says is a trainer's own name -> that trainer's picture.
--      Refused when two pictures share the name, so a generic "GRUNT" cannot
--      hand every grunt the admin's face -- the same rule as FRLG's picForName.
--   3. the object's own CLASS -> the class's picture.  Read off the object's
--      graphic's cart name, so it answers only when that name IS a class name.
--   4. the HAND-AUTHORED person table (emerald/gfx_art_people.lua): an exact
--      picture for a graphic no trainer wears, or a deliberate decline.  Runs
--      before the two statistical tables because a decision about this graphic
--      beats a majority over the ROM.
--   5. the (MAP, GRAPHIC) pair -> the picture the majority of THIS map's
--      trainers wearing that graphic have (emerald/map_art.lua).
--   6. the GRAPHIC alone -> the picture the majority of the whole ROM's
--      trainers wearing it have (emerald/gfx_art.lua).
--
-- Routes 5 and 6 are the ones that matter for the report, because the two and a
-- half thousand ordinary people have neither an id nor a name: their graphic is
-- the only fact about them, and it is what the cart dressed them in.  Route 4 is
-- what answers the people not one trainer wears -- the townsfolk, the nurse, the
-- gym leaders -- and what declines, honestly, the few the cart never drew.
--
-- ---- what is deliberately NOT here, and why it is not a gap
--
--   * no Emerald crop table.  art/crops.lua's framings are keyed to FRLG picture
--     numbers.  The engine's own `TrainerPic.front` already returns the cart's
--     picture at its own size, and main.lua's draw path frames whatever it is
--     handed, so the picture is used as the cart cut it.
--   * no Emerald CLASS-to-picture table of the FRLG kind, and no FRLG table used
--     as if it were an Emerald one.  Every table this module reads for an
--     Emerald answer is an Emerald table keyed by Emerald facts, and the
--     resolver still refuses on a non-Emerald boot by default.  A wrong face is
--     worse than none.  (1.3.3 adds a LAST-resort BORROW of a FireRed bust for
--     the few graphics Emerald has no bust for at all -- see route 7 below and
--     emerald/frlg_share.lua.  It is keyed by the Emerald GRAPHIC, never by an
--     id, because the two carts' id spaces disagree; it runs last, so it cannot
--     overrule a single Emerald answer; and it is off unless FireRed has been
--     imported.  It is a borrowing of art, not a conflation of data.)
--
-- The gap that REMAINS, stated rather than pretended away: Emerald's overworld
-- art is a SEPARATE set from its trainer busts, so a graphic worn by no trainer
-- (and named by no class) has no measured answer and gets NO portrait -- which
-- is this mod's rule everywhere the data does not decide.  Routes 4 and 5 cover
-- 69 of the 166 used person graphics; of the rest, the 13 kinds FireRed also drew
-- are borrowed by route 7, and the anonymous remainder still gets nothing.
-- Tests in tests/dp3_emerald_test.lua pin the contract either way: the resolver
-- declines with a non-empty, Emerald-naming reason rather than ever raising,
-- and it never answers an Emerald speaker from an FRLG DATA table.

local Emerald = {}

-- ---- injected dependencies
--
-- A mod's files are loaded with `load()` inside the mod's sandbox, where the
-- ambient `require` may or may not be the engine's.  Rather than guess, the
-- caller in main.lua hands this module a `require`, a mod reader and a logger
-- once, and the module uses those.  All are optional: with none, every route
-- that needs the engine reports "unknown", which is the safe answer -- unknown
-- is not Emerald, and not Emerald is not FireRed.
--
-- `Emerald.bind{ require = ..., log = ..., read = ... }` is called by main.lua
-- right after the chunk loads.  It is idempotent, so a double call is harmless.
local _require = nil
local _log = nil
local _read = nil
local _image = nil

function Emerald.bind(opts)
  opts = opts or {}
  if type(opts.require) == "function" then _require = opts.require end
  if type(opts.log) == "table" and type(opts.log.info) == "function" then
    _log = opts.log
  end
  if type(opts.read) == "function" then _read = opts.read end
  if type(opts.image) == "function" then _image = opts.image end
  return Emerald
end

-- A require that never raises: returns the module or nil.
local function safeRequire(name)
  local req = _require or require
  local ok, value = pcall(req, name)
  if ok and type(value) == "table" then return value end
  return nil
end

-- The game ids this module owns.  `emerald` is the id the engine uses (matching
-- the lowercase style of `firered` / `leafgreen` in GameVersion.VERSIONS).  The
-- two alternates are defensive spellings an engine or a future manifest might
-- use; accepting them costs nothing and stops a real Emerald boot being mistaken
-- for FireRed over a spelling.
Emerald.GAME_IDS = { emerald = true, pokemonemerald = true, pokeemerald = true }

-- The cart we verified this build against.  Recorded so a diagnostic can say
-- which dump was seen, and so the tests can assert the detector accepts it.
--   title   : "POKEMON EMER"
--   gamecode: "BPEE"   (USA/Europe revision 0)
--   sha1    : f3ae088181bf583e55daf962a92bb46f4f1d07b7
Emerald.CART_GAMECODE = "BPEE"
Emerald.CART_SHA1 = "f3ae088181bf583e55daf962a92bb46f4f1d07b7"

-- Human-readable name for logs and menu copy, so nothing has to spell it twice.
Emerald.DISPLAY_NAME = "Pokemon Emerald"

-- Where the generated Emerald tables live, relative to the mod root.  One
-- literal each, so the readers and the tests cannot drift apart.
Emerald.TRAINER_IDS_PATH = "emerald/trainer_ids.lua"
Emerald.GFX_ART_PATH    = "emerald/gfx_art.lua"
Emerald.MAP_ART_PATH    = "emerald/map_art.lua"
Emerald.GFX_NAMES_PATH  = "emerald/gfx_names.lua"
Emerald.PEOPLE_PATH     = "emerald/gfx_art_people.lua"
Emerald.FRLG_SHARE_PATH = "emerald/frlg_share.lua"

--- The version whose extracted cache a shared borrowing is read from.
--
-- A literal, so the reader and the tests cannot disagree about which cart the
-- borrow comes from.  It is the engine's own id for FireRed
-- (GameVersion.VERSIONS.firered.id), the same string its cachePrefix is built
-- from -- "firered/".
Emerald.SHARE_VERSION = "firered"

--- Where a FireRed front picture sits inside that cart's cache, relative to the
--- version prefix.  This is the same path the engine's own TrainerPic.front
--- builds (src/core/game3/trainer_pic.lua: cache_root() .. "/front/" .. pic),
--- so a borrowed picture is read exactly as FireRed reads its own.
--
-- The cache root is NOT written out here.  modkit's no-ROM-content gate (MK301,
-- 22-distribution-and-packaging.md) forbids a mod's own .lua from carrying the
-- ROM-derived cache's path as a literal -- a mod must ship its own art or derive
-- the path from the engine, never hard-code the player's generated tree.  So the
-- reader below DERIVES it from the engine's own module
-- (src.core.game3.cache_paths, the same CACHE_ROOT TrainerPic uses), and this
-- constant holds only the subpath beneath it.  A derivation, not a shadow.
--
-- The picture files are 64x64 RGBA, 16384 bytes each, and the reader below
-- checks the length rather than trusting the name.
Emerald.SHARE_PIC_SUB = "/trainers/front/"

--- EMERALD-NATIVE ART the mod ships, keyed by the graphics id it answers for.
--
-- The trainer tables answer with a BATTLE bust, and Emerald has no battle bust
-- for a great many story characters -- it has a hand-drawn 64x64 FIELD-EFFECT
-- portrait instead.  Professor Birch is the case that matters: the cart draws
-- him in `field_effect.o:sNewGameBirch_Gfx` (the art the game shows in Birch's
-- own new-game speech, and the FIRST face a new player ever sees), but his
-- overworld graphic wears no trainer class, so the measured tables cannot reach
-- that art and the old entry pointed him at pic 24 -- the "EXPERT", a kneeling
-- old woman, the wrong person by every measure.
--
-- These are shipped as PNGs under `emerald/art/` and loaded through the
-- injected `image` loader (main.lua passes `mod.assets:image`).  A graphic whose
-- entry lands here is served from the cart's own art, exactly as cut -- no crop,
-- no colour pipeline -- the same way FireRed's Fame Checker portraits are.
--
-- The value is the file name under `emerald/art/` WITHOUT the extension, so the
-- table is readable and the extension lives in one place (ART_DIR).
Emerald.ART_DIR = "emerald/art/"
Emerald.ASSET_ART = {
  [64] = "PROF_BIRCH",   -- PROF_BIRCH -> the cart's own sNewGameBirch_Gfx portrait
}

--- Is this game id an Emerald id?
--
-- Deliberately a pure function of the string so it can be unit-tested with no
-- engine at all, and so the caller has one place to ask.
function Emerald.isEmeraldId(id)
  return type(id) == "string" and Emerald.GAME_IDS[id:lower()] == true
end

--- The game id of the running process, or nil when the engine cannot say.
--
-- Two routes, in order of authority:
--
--   1. `GameVersion.get()` -- the engine's one source of truth for the active
--      version (src/core/GameVersion.lua).  This is what the importer, cache
--      mount and SaveData all read, so it is the answer that matters.
--   2. `Runtime._game` -- the live game3 service owner, which is what the mod
--      already reads in gameOf().  Used only when GameVersion is unavailable,
--      because a mod may be running under a sandbox that hides the module.
--
-- Returns the id as a string, or nil when neither route can answer.  A nil is
-- NOT Emerald and NOT FireRed -- the caller decides what an unknown game means;
-- this function only reports what it found.
function Emerald.detectGameId()
  local GameVersion = safeRequire("src.core.GameVersion")
  if GameVersion and GameVersion.get then
    local ok2, id = pcall(GameVersion.get)
    if ok2 and type(id) == "string" and id ~= "" then return id end
  end
  local Runtime = safeRequire("src.core.game3.runtime")
  if Runtime and type(Runtime._game) == "table" then
    local id = Runtime._game.gameId or Runtime._game.version or Runtime._game.id
    if type(id) == "string" and id ~= "" then return id end
  end
  return nil
end

--- Is the running game Emerald?
function Emerald.isRunning()
  return Emerald.isEmeraldId(Emerald.detectGameId())
end

-- ---- the diagnostic
--
-- One string per missing piece, built as data rather than assembled at each
-- call site so the tests can assert on the exact wording and a log line cannot
-- drift from the docs.
Emerald.MISSING_ENGINE_REASON =
  "this engine build has no Emerald import path, so no Emerald map objects, "
  .. "scripts or trainer pack can reach a mod"

Emerald.MISSING_TABLE_REASON =
  "the engine resolved Emerald, but " .. Emerald.TRAINER_IDS_PATH .. " is not "
  .. "in this build of the mod, so no Emerald script key can name a trainer"

Emerald.MISSING_PACK_REASON =
  "this Emerald boot has no trainer pack loaded yet, so an Emerald trainer id "
  .. "cannot be turned into the cart's picture number"

--- Why no portrait can be resolved on this Emerald boot, or nil when there IS
--- a reason to try.
--
-- Returning a reason is the SAFE answer: the caller draws a bare box, which is
-- what the game looks like with no portrait mod, rather than a wrong face.
--
-- The order mirrors the resolver: engine first, then the mod's own table, then
-- the engine's pack.  Each answer names the piece that is actually missing, so
-- a player or a bug report can tell "the engine is too old" apart from "the pack
-- has not been generated yet".
function Emerald.unsupportedReason()
  local GameVersion = safeRequire("src.core.GameVersion")
  if not (GameVersion and type(GameVersion.VERSIONS) == "table"
      and type(GameVersion.VERSIONS.emerald) == "table") then
    return Emerald.MISSING_ENGINE_REASON
  end
  if not Emerald.trainerIds() then return Emerald.MISSING_TABLE_REASON end
  return nil
end

-- ---- the Emerald trainer table
--
-- Read once, lazily, through the injected mod reader -- a mod's files are not on
-- package.path, so this is the same `mod:read` + `load` route main.lua uses for
-- art/trainer_ids.lua and art/crops.lua.  `false` records a failed attempt so a
-- missing table is not re-read on every box.
local _ids = nil

function Emerald.trainerIds()
  if _ids ~= nil then return _ids or nil end
  _ids = false
  if type(_read) ~= "function" then return nil end
  local ok, source = pcall(_read, Emerald.TRAINER_IDS_PATH)
  if ok and type(source) == "string" then
    local chunk = load(source, "@" .. Emerald.TRAINER_IDS_PATH)
    if chunk then
      local ok2, value = pcall(chunk)
      if ok2 and type(value) == "table" then _ids = value end
    end
  end
  if _log then
    if _ids then
      local n = 0
      for _ in pairs(_ids) do n = n + 1 end
      _log:info("emerald: loaded %s (%d entries)", Emerald.TRAINER_IDS_PATH, n)
    else
      _log:info("emerald: %s not available; %s", Emerald.TRAINER_IDS_PATH,
        Emerald.MISSING_TABLE_REASON)
    end
  end
  return _ids or nil
end

-- ---- the generated Emerald data tables
--
-- Same reader as trainerIds, generalised: a mod's files are not on
-- package.path, so each is read through the injected `_read` and `load`ed, and a
-- failure is remembered so a missing table is not re-read on every box.  A table
-- that is absent is NOT an error -- an older build of the mod simply has no
-- answer for the routes it feeds, and on a real Emerald boot that is a bare box,
-- never a crash.
local _tables = {}

local function loadTable(path)
  if _tables[path] ~= nil then return _tables[path] or nil end
  _tables[path] = false
  if type(_read) ~= "function" then return nil end
  local ok, source = pcall(_read, path)
  if ok and type(source) == "string" then
    local chunk = load(source, "@" .. path)
    if chunk then
      local ok2, value = pcall(chunk)
      if ok2 and type(value) == "table" then _tables[path] = value end
    end
  end
  if _log then
    if _tables[path] then
      local n = 0
      for _ in pairs(_tables[path]) do n = n + 1 end
      _log:info("emerald: loaded %s (%d entries)", path, n)
    else
      _log:info("emerald: %s not available", path)
    end
  end
  return _tables[path] or nil
end

--- Emerald graphics id -> the picture it means (emerald/gfx_art.lua), or nil.
-- Keyed by the cart's graphics number, values are front-picture ids.
function Emerald.gfxArt()   return loadTable(Emerald.GFX_ART_PATH)   end
--- (Emerald map id, graphics id) -> picture (emerald/map_art.lua), or nil.
function Emerald.mapArt()   return loadTable(Emerald.MAP_ART_PATH)   end
--- Emerald graphics id -> the cart's name for it (emerald/gfx_names.lua), or nil.
function Emerald.gfxNames() return loadTable(Emerald.GFX_NAMES_PATH) end
--- Emerald graphics id -> an EXACT picture, or `false` to decline the graphic
--- (emerald/gfx_art_people.lua).  Hand-authored, so it OUTRANKS the generated
--- majorities -- see the file's header for why and how its values were decided.
function Emerald.peopleArt() return loadTable(Emerald.PEOPLE_PATH) end

--- Emerald graphics id -> a FIRE RED front-picture id to borrow, or nil
--- (emerald/frlg_share.lua).  Hand-authored, art-verified, and deliberately
--- SHORT: it holds only the graphics the Emerald cart never drew a bust of and
--- FireRed did.  See the file's header for how each value was decided, and for
--- why sharing is keyed by graphic rather than by class or picture id.
function Emerald.shareArt() return loadTable(Emerald.FRLG_SHARE_PATH) end

-- The mod's OWN Emerald art for a graphics id, loaded as an engine image.
--
-- Unlike every other route in this module, this one does not go through the
-- engine's trainer pack: the file is a 64x64 PNG the mod ships under
-- `emerald/art/`, and it is drawn exactly as cut (no crop table, no colour
-- pipeline) -- the same treatment main.lua gives a FireRed Fame Checker
-- portrait.  Returns the art table main.lua's picArt shape expects, or nil when
-- the graphic has no shipped art OR no loader was bound (a headless load must
-- not fail just because there is no graphics context).
--
-- `false` in ASSET_ART is a deliberate decline, matching the other tables.
function Emerald.assetArtFor(gfx)
  gfx = tonumber(gfx)
  if not gfx then return nil end
  local entry = Emerald.ASSET_ART[gfx]
  if entry == nil or entry == false then return nil end
  if type(_image) ~= "function" then return nil end
  local ok, image = pcall(_image, Emerald.ART_DIR .. entry .. ".png")
  if not ok or image == nil then return nil end
  local ok2, w, h = pcall(function() return image:getDimensions() end)
  if not ok2 then return nil end
  w, h = tonumber(w), tonumber(h)
  if not w or not h or w <= 0 or h <= 0 then return nil end
  return { image = image, w = w, h = h, asset = entry }
end

-- The trainer id for a speaker's script, or nil.  Pure table lookup, no engine
-- reach, so it can be tested with a stub table.
function Emerald.trainerIdFor(speaker)
  if type(speaker) ~= "table" then return nil end
  local explicit = tonumber(speaker.trainerId)
  if explicit and explicit > 0 then return explicit end
  local key = speaker.scriptKey
  if type(key) ~= "string" or key == "" then return nil end
  local ids = Emerald.trainerIds()
  if not ids then return nil end
  local tid = tonumber(ids[key])
  if tid and tid > 0 then return tid end
  return nil
end

-- The cart's picture number for a trainer id, read from the engine's own
-- Emerald trainer pack.
--
-- ---- THE GUARD IS `pic >= 0`, NOT `pic > 0`, AND THAT IS EMERALD-SPECIFIC
--
-- The FRLG side refuses picture 0 because FRLG's picture 0 is its NULL picture:
-- every row the cart left empty carries it, and `0` is truthy in Lua, so a
-- lookup that only asked "is there a number?" would hand every empty row a blank
-- face.  EMERALD IS NOT FRLG, and copying that rule onto it was this module's
-- second defect.
--
-- In Emerald picture 0 is a REAL picture: the HIKER bust, worn by the class-2
-- HIKER (trainer 1 SAWYER and 43 others) -- measured by .probe/dp3_emerald_pics.lua
-- against the player's own ROM.  Emerald marks "no picture" with NEGATIVE
-- sentinels, not with 0, so 0 is an ordinary id here and refusing it silently
-- stripped the face from every Hiker in Hoenn.  The guard is therefore
-- `pic >= 0`, and the ONLY value that is "no picture" is one that is absent or
-- negative -- which is what `TrainerPic.front` itself enforces (`picId < 0`).
--
-- Class 0 still means "not a trainer" and is not a mapping: that part of the
-- FRLG rule is about the CLASS space, and the class spaces do agree on it.
--
-- The module is `src.core.game3.scripting.trainers` -- the SAME service
-- main.lua's FRLG path reads for its own id->picture leg, so the two games are
-- translated by one implementation and a change to it cannot drift apart from
-- itself.  The pack is keyed `trainers[id] = { class=, className=, pic=, name= }`.
function Emerald.picForTrainerId(tid)
  tid = tonumber(tid)
  if not tid or tid <= 0 then return nil end
  local pack = Emerald.trainerPack()
  if not pack then return nil end
  local row = type(pack.trainers) == "table" and pack.trainers[tid] or nil
  if type(row) ~= "table" then return nil end
  if tonumber(row.class) and tonumber(row.class) <= 0 then return nil end
  local pic = tonumber(row.pic)
  if pic and pic >= 0 then return pic end
  return nil
end

--- The engine's trainer pack, or nil.  Exposed (and name-recorded) so a real
--- boot that cannot reach it says WHICH piece was unreachable rather than
--- looking like an empty table.  Cached only on success: the pack is a
--- generated cache, so a first ask that precedes it must be repeatable.
local _pack, _packErr = nil, nil

function Emerald.trainerPack()
  if _pack ~= nil then return _pack end
  local Trainers = safeRequire("src.core.game3.scripting.trainers")
  if not (Trainers and Trainers.pack) then
    _packErr = "src.core.game3.scripting.trainers is not reachable from this mod"
    return nil
  end
  local ok, pack = pcall(Trainers.pack)
  if not ok or type(pack) ~= "table" then
    _packErr = "the engine's trainer pack is not generated for this boot yet"
    return nil
  end
  _pack, _packErr = pack, nil
  return _pack
end

--- Why the pack could not be read, for a diagnostic; nil when it could.
function Emerald.trainerPackError() return _packErr end

-- ---- the pack index: class -> picture, name -> picture
--
-- The Emerald counterpart of main.lua's loadPackIndex, built from the same
-- pack.  Two maps, both decided by the cart's own rows:
--
--   byClass[classId]  = the picture the class pins, or the most common of the
--                       ones it pins (Emerald's LEADER class holds every gym
--                       leader, so a class alone cannot tell them apart -- the
--                       graphic does, and route 4/5 is what separates them).
--   byName[name]      = a trainer's own picture, or `false` when two pictures
--                       share the name.  `false` is "ambiguous" as against
--                       nil's "unknown": a name that does not name anybody in
--                       particular must not answer, or a generic "GRUNT" would
--                       hand every grunt the admin's face.
--
-- Built lazily and cached, because it walks 855 rows.  A missing pack yields an
-- index of empty maps rather than nil, so the callers stay branch-free.
local _index = nil

function Emerald.packIndex()
  if _index then return _index end
  local index = { byClass = {}, byName = {}, classNames = {}, classRows = {} }
  _index = index
  local pack = Emerald.trainerPack()
  if not pack then return index end

  local classNames = pack.classNames
  if type(classNames) == "table" then
    for id, name in pairs(classNames) do
      local cid = tonumber(id)
      if cid and type(name) == "string" and name ~= "" then
        index.classNames[cid] = name:upper()
      end
    end
  end

  local classCount = {}   -- class id -> picture -> rows
  for _, row in pairs(type(pack.trainers) == "table" and pack.trainers or {}) do
    if type(row) == "table" then
      local cls  = tonumber(row.class)
      local pic  = tonumber(row.pic)
      -- pic >= 0, not > 0: Emerald's 0 is the Hiker's real picture (see
      -- picForTrainerId for the measurement and the reasoning).
      if pic and pic >= 0 then
        if cls and cls > 0 then
          local slot = classCount[cls]
          if not slot then slot = {}; classCount[cls] = slot end
          slot[pic] = (slot[pic] or 0) + 1
        end
        local name = row.name
        if type(name) == "string" and name ~= "" then
          local key = name:upper()
          local known = index.byName[key]
          if known == nil then
            index.byName[key] = pic
          elseif known ~= pic then
            -- Two pictures under one name: it names nobody in particular.
            index.byName[key] = false
          end
        end
      end
      if cls and cls > 0 then
        index.classRows[cls] = (index.classRows[cls] or 0) + 1
      end
    end
  end

  -- The class's picture: the one the most rows wear, ties to the lower id so
  -- the answer is stable across runs (pairs() order is not).
  for cls, counts in pairs(classCount) do
    local bestPic, bestN
    for pic, n in pairs(counts) do
      if bestN == nil or n > bestN or (n == bestN and pic < bestPic) then
        bestPic, bestN = pic, n
      end
    end
    index.byClass[cls] = bestPic
  end

  return index
end

-- Class id -> front-pic id, through the pack.  Exact when the class pins one
-- picture; the most common of them when it pins several.
function Emerald.picForClass(classId)
  classId = tonumber(classId)
  if not classId then return nil end
  return Emerald.packIndex().byClass[classId]
end

-- Class NAME -> class id, so a graphic's cart name can be tried as a class name
-- the way FRLG's classIdForName does.  Emerald's class table has no duplicated
-- names (measured: 66 classes, 66 distinct uppercased names), so the plain
-- inverse is exact and needs no row-count tie-break.
function Emerald.classIdForName(name)
  if type(name) ~= "string" or name == "" then return nil end
  local key = name:upper()
  local names = Emerald.packIndex().classNames
  for cid, n in pairs(names) do
    if n == key then return cid end
  end
  return nil
end

-- A trainer's own name -> front-pic id.  nil when the name is unknown OR worn
-- by two different pictures -- see packIndex.
function Emerald.picForName(name)
  if type(name) ~= "string" or name == "" then return nil end
  local pic = Emerald.packIndex().byName[name:upper()]
  if pic == false then return nil end
  return pic
end

-- The portrait for a picture number, in exactly the shape main.lua's picArt
-- returns: `{ image = <Image>, w = <number>, h = <number>, pic = <number> }`,
-- or nil.  Read through the engine's trainer-pic service, which is what turns a
-- cart picture id into a texture; it is pcall'd because a headless or
-- half-initialised boot must not turn a portrait lookup into an error.
--
-- `pic < 0` is the only refusal: the engine's own TrainerPic.front takes any id
-- >= 0 (picture 0 is the Hiker), and a negative id is Emerald's "no picture"
-- sentinel.  Refusing 0 here would re-introduce the defect this module fixed.
function Emerald.artForPic(pic)
  pic = tonumber(pic)
  if not pic or pic < 0 then return nil end
  local TrainerPic = safeRequire("src.core.game3.trainer_pic")
  if not (TrainerPic and TrainerPic.front) then return nil end
  local ok, entry = pcall(TrainerPic.front, pic)
  if ok and type(entry) == "table" and entry.image then
    return { image = entry.image, w = entry.w, h = entry.h, pic = pic }
  end
  return nil
end

-- ---- SHARED FireRed art: a borrowed bust, read from the other cart's cache
--
-- ---- why this is a read and not a mount
--
-- The engine mounts exactly ONE game version's cache at a time
-- (src/import/CacheFs.lua: mountVersion / unmountVersion, whose own comment says
-- "a process normally mounts exactly one version and then boots it").  During an
-- Emerald boot the FireRed subtree is therefore NOT on the read path, and
-- src/core/game3/trainer_pic.lua -- which reads through the ONE active cache --
-- cannot see it.  That is by design: the alternative, mounting FireRed's tree
-- under an Emerald boot, is the exact confusion unmountVersion warns about.
--
-- The engine's sanctioned way to read another version's cache without mounting
-- it is CacheFs.readAt, whose own comment says it reads "an exact
-- version-qualified path without consulting CacheFs.prefix", and which the dex
-- already uses for precisely this (src/core/game3/dex.lua:40).  So a borrowed
-- bust is read here as the FireRed version prefix, then the engine's own cache
-- root (src.core.game3.cache_paths.CACHE_ROOT, the same one TrainerPic uses),
-- then SHARE_PIC_SUB and the picture id -- e.g. "firered/" .. root ..
-- "/trainers/front/<pic>.rgba".  The root is derived rather than written, so no
-- generated-tree path appears as a literal in this file (modkit MK301).
--
-- which is a plain file read: nothing is mounted, no global is touched, and an
-- Emerald boot that never touches this path is byte-for-byte what it was.
--
-- ---- the texture
--
-- The bytes are 64x64 RGBA (16384 of them).  The engine's own
-- TrainerPic.front turns such bytes into an Image with love.image.newImageData
-- + love.graphics.newImage and a nearest filter; that is a few lines and it is
-- not reachable from a mod (the mod's sandbox has no love.image guarantee), so
-- this builds the texture through the SAME injected `image` service route 3b
-- uses -- except route 3b loads a file by relative path, and this needs an
-- Image from bytes.  main.lua therefore binds a small factory behind the same
-- seam, and this function calls it.  When no factory is bound -- a headless
-- load, or an engine build without the seam -- the route answers nil, which is
-- the safe answer: a bare box, never a crash and never a wrong face.
--
-- `pic` is validated before any read: a negative id is FireRed's no-picture
-- sentinel, and the value is additionally checked against the file's real
-- length so a truncated or absent cache entry misses rather than half-loads.
local _shareFactory = nil

--- Bind the byte->Image factory the shared route needs.  Called by main.lua
--- alongside the other bind() fields; `nil` clears it, which restores the
--- "no sharing" behaviour (the safe default on any boot that cannot build a
--- texture).  Kept separate from bind()'s `image`, because that one loads a
--- FILE by relative path and this one builds an Image from BYTES.
function Emerald.bindShareImage(factory)
  _shareFactory = (type(factory) == "function") and factory or nil
  return Emerald
end

--- Read a FireRed front picture's bytes out of the FIRERED cache, or nil.
--
-- Returns the 16384 bytes for a 64x64 picture, or nil when FireRed has not been
-- imported (no cache), the picture does not exist, or the entry is short.  The
-- read goes through the engine's CacheFs.readAt, which is a pure, prefixed file
-- read; a mod may not have CacheFs reachable (a sandbox), in which case this
-- returns nil -- again, the safe answer.
function Emerald.shareBytes(pic)
  pic = tonumber(pic)
  if not pic or pic < 0 then return nil end
  local CacheFs = safeRequire("src.import.CacheFs")
  if not (CacheFs and CacheFs.readAt) then return nil end
  -- The cache ROOT is derived from the engine's own module, never written here:
  -- MK301 forbids a mod's .lua carrying the ROM-derived path as a literal.  This
  -- is the same CACHE_ROOT the engine's TrainerPic.front uses, so the borrowed
  -- path is built exactly as FireRed builds its own -- and it follows the
  -- engine's setRoot indirection rather than shadowing it.
  local CachePaths = safeRequire("src.core.game3.cache_paths")
  local root = CachePaths and CachePaths.CACHE_ROOT
  if type(root) ~= "string" or root == "" then return nil end
  local GameVersion = safeRequire("src.core.GameVersion")
  local info = GameVersion and GameVersion.info and GameVersion.info(Emerald.SHARE_VERSION)
  local prefix = (info and info.cachePrefix) or (Emerald.SHARE_VERSION .. "/")
  local rel = prefix .. root .. Emerald.SHARE_PIC_SUB .. tostring(pic) .. ".rgba"
  local ok, bytes = pcall(CacheFs.readAt, rel)
  if not ok or type(bytes) ~= "string" then return nil end
  if #bytes < 64 * 64 * 4 then return nil end
  return bytes
end

--- The borrowed FireRed portrait for an EMERALD graphics id, in the shape
--- main.lua's picArt returns (`{ image =, w =, h =, pic = }`), or nil.
--
-- `gfx` is looked up in emerald/frlg_share.lua; a graphic absent from that table
-- is NOT borrowed (the Emerald decline stands).  The picture id it names is then
-- read from the FireRed cache and turned into a texture.  Every failure --
-- no table, no entry, no FireRed cache, a short read, no image factory -- is a
-- plain nil, because a missing portrait is the mod's rule everywhere the data
-- does not decide, and a borrowed wrong face would be worse than none.
--
-- The returned `pic` is the FIRERED picture id, and `share = "firered"` records
-- where it came from, so a diagnostic (and the tests) can tell a borrowed face
-- from an Emerald one at a glance.
function Emerald.shareArtFor(gfx)
  gfx = tonumber(gfx)
  if not gfx then return nil end
  local share = Emerald.shareArt()
  if type(share) ~= "table" then return nil end
  local pic = share[gfx]
  if pic == nil or pic == false then return nil end
  if type(_shareFactory) ~= "function" then return nil end
  local bytes = Emerald.shareBytes(pic)
  if not bytes then return nil end
  local ok, image = pcall(_shareFactory, bytes, 64, 64)
  if not ok or image == nil then return nil end
  return { image = image, w = 64, h = 64, pic = tonumber(pic), share = Emerald.SHARE_VERSION }
end

--- Resolve a portrait for an Emerald speaker.
--
-- The Emerald counterpart of main.lua's FRLG `artFor`, running the same four
-- routes in the same order, made from Emerald facts:
--
--   1. scriptKey -> trainer id -> that trainer's picture.  Exact.
--   2. the box's own NAME -> that trainer's picture (ambiguous names refused).
--   3. the graphics id's cart NAME -> a class -> the class's picture.  This is
--      the step FRLG calls the class route, and it is why a Hiker, a Lass or a
--      Beauty gets the right bust from the graphic alone: the cart's name for
--      gfx 55 IS "HIKER".
--   4. the (map, graphics) pair -> the picture this map's trainers wearing that
--      graphic have in the majority (emerald/map_art.lua).
--   5. the graphics id alone -> the picture the whole ROM's trainers wearing it
--      have in the majority (emerald/gfx_art.lua).
--
-- 4 and 5 are what answer the 2,353 ordinary people routes 1-3 cannot name, and
-- they are the fix for the report ("no portraits has been showing").  Each is a
-- MEASURED majority over the cart's own rows, so it can be wrong for a minority
-- by construction -- exactly FRLG's GFX_ART trade-off, and better than a bare
-- box for everybody.
--
-- Returns `art` on success, or `nil, reason` when it cannot.  It never raises,
-- and it never consults an FRLG table.
--
-- THE GAME CHECK IS PART OF THE RESOLVER, not left to the caller.  `opts.force`
-- exists for a caller that has already asked `isRunning()` itself -- main.lua
-- does exactly that, one branch above -- but the DEFAULT is to refuse on a boot
-- that is not Emerald.  That is deliberate: the brief's rule is that Emerald
-- data must never stand in for FRLG data, and a resolver that answered whenever
-- its own tables happened to be loadable would make that rule a property of
-- every call site rather than of this module -- one wiring mistake away from an
-- Emerald face on a FireRed cart.  A non-Emerald boot therefore gets `nil` with
-- no reason string, because nothing is missing: this is simply not our game,
-- and the FRLG path is the one that should answer.
function Emerald.artFor(speaker, opts)
  if type(speaker) ~= "table" then return nil, Emerald.unsupportedReason() end

  if not (type(opts) == "table" and opts.force) and not Emerald.isRunning() then
    return nil
  end

  local reason = Emerald.unsupportedReason()
  if reason then return nil, reason end

  local function viaPic(pic)
    if pic == nil or pic == false then return nil end
    return Emerald.artForPic(pic)
  end

  -- 1. the OBJECT's scriptKey -> its trainer -> its picture.
  local tid = Emerald.trainerIdFor(speaker)
  if tid then
    local art = viaPic(Emerald.picForTrainerId(tid))
    if art then return art end
    -- The id was known but the pack could not turn it into a picture: that is a
    -- real diagnostic, not an ordinary "no portrait".  Fall through to the
    -- routes below first -- a graphic answer is better than none -- and only
    -- report the pack failure if nothing else answers.
  end

  -- 2. the box's own NAME -> that trainer's picture.  Step 1 outranks it (an id
  --    is a person, a name can be shared), which is why it is asked second.
  local nameArt = viaPic(Emerald.picForName(speaker.name))
  if nameArt then return nameArt end

  -- 3. the graphics id's cart name -> a class -> the class's picture.
  local gfx = tonumber(speaker.gfx)
  local gfxName
  if gfx then
    local names = Emerald.gfxNames()
    gfxName = names and names[gfx] or nil
    if type(gfxName) == "string" and gfxName ~= "" then
      local classArt = viaPic(Emerald.picForClass(Emerald.classIdForName(gfxName)))
      if classArt then return classArt end
    end
  end

  -- 3b. the mod's OWN Emerald art for this graphic, when it ships one.
  --
  --     This is the cart's own field-effect portrait, served as a PNG.  It runs
  --     here -- after the ID and NAME routes (an id or a name is a person, and
  --     a person beats a graphic) but BEFORE the hand table -- because for the
  --     graphics it covers it is EXACT art from the cart, where the hand table's
  --     answer is a closest-build compromise by construction.  Professor Birch
  --     is the case: the cart draws him in field_effect.o:sNewGameBirch_Gfx, and
  --     that drawing is the first face a new player sees.
  if gfx then
    local assetArt = Emerald.assetArtFor(gfx)
    if assetArt then return assetArt end
  end

  -- 4. the HAND-AUTHORED person table.  It runs BEFORE the two generated
  --    majorities because a hand entry is a decision about THIS graphic, and the
  --    majorities are statistical answers that are wrong for a minority by
  --    construction.  It is what answers the 25 kinds whose graphic no trainer
  --    wears -- the townsfolk, the nurse, the leaders -- and its `false` is a
  --    real decline (a person the cart drew no bust of), so it stops the routes
  --    below rather than falling through to a majority that would put a wrong
  --    face on a shop clerk.
  --
  --    THE DECLINE IS WHERE THE BORROW BELONGS.  `false` says "this cart drew no
  --    bust of this kind" -- which is EXACTLY the case a FireRed borrow exists
  --    for (emerald/frlg_share.lua).  So a declined graphic is offered the
  --    hand-authored, art-verified borrow BEFORE the statistical routes 5 and 6
  --    are allowed to guess: a borrowed bust of the RIGHT KIND is strictly better
  --    than a whole-ROM majority, which is a wrong face for a minority by
  --    construction.  Only if there is no borrow does the decline stand and stop
  --    5/6.  (Attempting the borrow after 5/6 instead would be dead code: `false`
  --    returns, so the 13 graphics the share table names would never reach a
  --    route placed below this one.)
  if gfx then
    local people = Emerald.peopleArt()
    if type(people) == "table" then
      local peoplePic = people[gfx]
      if peoplePic == false then
        local shared = Emerald.shareArtFor(gfx)
        if shared then return shared end
        return nil
      end
      local peopleArt = viaPic(peoplePic)
      if peopleArt then return peopleArt end
    end
  end

  -- 5. the (map, graphics) pair.  A map is more specific than the whole ROM, so
  --    this runs before the graphic-alone route.
  if gfx then
    local mapId = speaker.mapId
    if type(mapId) == "string" and mapId ~= "" then
      local maps = Emerald.mapArt()
      local onMap = maps and maps[mapId]
      if type(onMap) == "table" then
        local mapPic = onMap[gfx]
        if mapPic == false then return nil end   -- declined on this map
        local mapArt = viaPic(mapPic)
        if mapArt then return mapArt end
      end
    end
  end

  -- 6. the graphics id alone -- the whole-ROM majority.  LAST, because it is the
  --    least specific fact about the person.
  if gfx then
    local gfxArtTbl = Emerald.gfxArt()
    if gfxArtTbl then
      local gfxPic = gfxArtTbl[gfx]
      if gfxPic == false then return nil end   -- declined for the graphic itself
      local gfxArt = viaPic(gfxPic)
      if gfxArt then return gfxArt end
    end
  end

  -- 7. the SHARED FireRed bust -- the sweep for a graphic with no hand entry.
  --
  --    Route 4 already offers the borrow to any graphic it DECLINES with `false`
  --    (that is where the 13 shared graphics are answered, because all 13 are
  --    `false` in the hand table).  This route is the complement: a graphic the
  --    hand table has NO ENTRY for at all -- neither an answer nor a decline --
  --    that the two statistical routes above also could not answer.  It runs
  --    LAST because every route above is a fact about THIS cart, and a fact
  --    about the cart you are playing beats a borrowed face from another one; it
  --    borrows only what emerald/frlg_share.lua names, so a graphic absent from
  --    that table is simply not borrowed and the ordinary decline stands.
  --
  --    If FireRed was never imported, this misses (no cache to read) and the
  --    answer is the bare box it was before sharing existed -- never an error.
  if gfx then
    local shared = Emerald.shareArtFor(gfx)
    if shared then return shared end
  end

  -- Nothing answered.  Report the pack failure only if the failure was about a
  -- trainer we DID identify (an id route that had a row but no readable
  -- picture); otherwise this is the ordinary "the cart never drew this person",
  -- which carries no reason string, exactly as the FRLG path declines silently.
  if tid and not Emerald.picForTrainerId(tid) then
    return nil, Emerald.trainerPackError() or Emerald.MISSING_PACK_REASON
  end
  return nil
end

--- Would Emerald portraits be drawn at all this boot?  True only when the engine
--- can resolve Emerald AND the mod has its Emerald table.  A single predicate so
--- the caller has one place to branch rather than re-deriving the rule.
function Emerald.canDrawPortraits()
  return Emerald.isRunning() and Emerald.unsupportedReason() == nil
end

return Emerald
